wechat:
  mpAppId: wxd898xxxx
  mchId: 1483xxxx
  mchKey: C5245D70xxxxx
  keyPath: /var/weixin_cert/wxpay.p12
  notifyUrl: http://xxx.com/notify
  miniAppId: wxxxxxxxxxxx6bf9b
  miniAppSecret: xxbc6xxxxxxxxxxxxxx9c49d
  appAppId: wxxxxxxxxxxxx43b0

alipay:
  appId: appId
  privateKey: 商户私钥
  aliPayPublicKey: 支付宝公钥
  notifyUrl: http://xxx.com/notify